{
 "title": "Executive Sales Overview",
 "time": { "from": "2002-12-31T23:00:00.000Z", "to": "2005-12-31T22:59:59.000Z" },
 "panels": [
  {
   "title": "Monthly Sales Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT TO_CHAR(order_date, 'YYYY-MM') AS month, SUM(sales) FROM sales_data GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Average Order Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT AVG(total_order_sales) \r\nFROM (SELECT order_number, SUM(sales) as total_order_sales FROM sales_data GROUP BY order_number) sub;"
    }
   ]
  },
  {
   "title": "Revenue Trend (Daily)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT order_date AS \"time\", SUM(sales) \r\nFROM sales_data \r\nWHERE $__timeFilter(order_date) \r\nGROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT SUM(sales) FROM sales_data;"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT COUNT(DISTINCT order_number) FROM sales_data;"
    }
   ]
  }
 ]
}