{
 "title": "Geographical Analysis",
 "time": { "from": "2002-12-31T23:00:00.000Z", "to": "2005-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT country FROM sales_data ORDER BY country;"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg Order Frequency per Country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT country, COUNT(*)::float/COUNT(DISTINCT customername) AS avg_orders_per_customer FROM sales_data GROUP BY country;"
    }
   ]
  },
  {
   "title": "Market Share (Territory)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT \r\n    COALESCE(territory, 'Other/NA') AS territory_name, \r\n    SUM(sales) AS total_revenue\r\nFROM sales_data \r\nGROUP BY territory\r\nORDER BY total_revenue DESC;"
    }
   ]
  },
  {
   "title": "Top 10 Cities (${country})",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT\r\n  city,\r\n  SUM(sales) AS total_sales\r\nFROM sales_data\r\nWHERE\r\n  (${country:singlequote} = 'ALL'\r\n   OR country = ${country:singlequote})\r\nGROUP BY city\r\nORDER BY total_sales DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Countries",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT country, SUM(sales) as revenue FROM sales_data GROUP BY country ORDER BY revenue DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Revenue by Country",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT country, SUM(sales) FROM sales_data GROUP BY country"
    }
   ]
  }
 ]
}