{
 "title": "Regional & Customer Insights",
 "time": { "from": "2002-12-31T23:00:00.000Z", "to": "2005-12-31T22:59:59.000Z" },
 "panels": [
  {
   "title": "Sales by Day of Week",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT TO_CHAR(order_date, 'Day') as day_name, SUM(sales) FROM sales_data GROUP BY 1, EXTRACT(DOW FROM order_date) ORDER BY EXTRACT(DOW FROM order_date)"
    }
   ]
  },
  {
   "title": "Cancellation Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT order_date AS time, COUNT(*) FROM sales_data WHERE status = 'Cancelled' GROUP BY 1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "Large Deal Ratio (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT (COUNT(*) FILTER (WHERE deal_size = 'Large')::float / COUNT(*)) * 100 FROM sales_data"
    }
   ]
  },
  {
   "title": "Top 10 Customers by Revenue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT customername, SUM(sales) as lifetime_value \r\nFROM sales_data \r\nGROUP BY customername \r\nORDER BY lifetime_value DESC \r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Order Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sales_db",
     "rawSql": "SELECT status, COUNT(DISTINCT order_number) \r\nFROM sales_data \r\nGROUP BY status;"
    }
   ]
  }
 ]
}